<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index</title>
</head>
<body style="background-color: white;">
    <div style="font-family: Arial, Helvetica, sans-serif; display: flex; justify-content: center; flex-direction: column; text-align: center; border: clear; background-color: white">
        <div>
            <h1>Fake Deetz</h1>
        </div>
        <div style="font-family: Arial; font-size: 15px; font-weight: 400; display: flex; flex-direction: row; justify-content: center; align-items: center; height: 44px; background-color: #2B547E;">
            <a href="http://localhost/10DGS-Fake-Deets-Project/Home/index.php" style="text-decoration: none; margin-left: 70px; margin-right: 70px"><font color="#FFD700">Home</a>
            <a href="http://localhost/10DGS-Fake-Deets-Project/Home/generator.php" style="text-decoration: none; margin-right: 70px;"><font color="#fafafa">Generator</a>
            <a href="http://localhost/10DGS-Fake-Deets-Project/Admin/admin.php" style="text-decoration: none; margin-right: 70px;"><font color="#fafaf">Admin</a>
        </div>
        <font color="#000">
        <div style="padding-top: 5%">
            <h2>Welcome to Fake Deetz!</h2>
            <label>Fake Deetz is a free to use service that randomly generates fake user profiles.<br> 
            All fake user profiles are not based or taken from real people or users,<br> all fake profile 
            photos are created and generated by an A.I.<br> To generate a fake user go to the generator page and press the
            generate button.</label>
        </div>
        </font>
    </div>
</body>
</html> 